#!/bin/sh

#
# .xinitrc - X Window System initialization script
#

# Set file paths for user modmap, system resources, and system modmap
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge system Xresources and apply modmap files if they exist
[[ -f $sysresources ]] && xrdb -merge $sysresources
[[ -f $sysmodmap ]] && xmodmap $sysmodmap
[[ -f $usermodmap ]] && xmodmap $usermodmap

# Execute scripts in the xinitrc.d directory if it exists
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

source "$HOME/.local/lib/user-xinitrc.sh"
