#!/bin/sh

usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[[ -f $sysresources ]] && xrdb -merge $sysresources
[[ -f $sysmodmap ]] && xmodmap $sysmodmap
[[ -f $usermodmap ]] && xmodmap $usermodmap

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# ------------------------------------------------------------------------------

# Keyboard and screen configuration
setxkbmap us
xrandr --output eDP-1 --auto --output HDMI-1 --off

# Continuously update root window name every 1 minute
while true; do
  xsetroot -name "$(date "+%F %R")"
  sleep 1m
done &

# Execute the window manager
exec dwm
